site_name: Next-Exam Wiki
theme:
  name: material
  language: de
  logo: images/next-exam-logo.png
  favicon: images/next-exam-logo.png
  palette:
    primary: white
plugins:
  - search
extra:
  generator: false
